version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:302860c78743e6e57f865c2ca5720ac26bc78180ada08f20518aa9fec80e3fc2
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Test Code
          command: npm test
      - deploy:
          name: Release Code
          command: npm run release
