version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:501e4ed639803732e0c8f40d3e1e93cf8b0ebbf89790023770aa68dbd0603626
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Test Code
          command: npm test
      - deploy:
          name: Release Code
          command: npm run release
