version: 2
machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:46b1a834cd0b597720838bd3ff5ca74867afcca2c3ccf48049d71379fd57d03c
    environment:
      - NPM_CONFIG_LOGLEVEL: warn
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Test Code
          command: npm test
      - deploy:
          name: Release Code
          command: npm run release
